export const FORTUNE_500_CAREER_SITES = [
  { company: 'Amazon', domain: 'amazon.jobs' },
  { company: 'Apple', domain: 'jobs.apple.com' },
  { company: 'Walmart', domain: 'careers.walmart.com' },
  { company: 'UnitedHealth Group', domain: 'careers.unitedhealthgroup.com' },
  { company: 'CVS Health', domain: 'jobs.cvshealth.com' },
  { company: 'ExxonMobil', domain: 'jobs.exxonmobil.com' },
  { company: 'JPMorgan Chase', domain: 'careers.jpmorgan.com' },
  { company: 'Microsoft', domain: 'careers.microsoft.com' },
  { company: 'Google', domain: 'careers.google.com' },
  { company: 'Meta', domain: 'www.metacareers.com' },
  { company: 'IBM', domain: 'www.ibm.com' },
  { company: 'Oracle', domain: 'www.oracle.com' },
  { company: 'Intel', domain: 'jobs.intel.com' },
  { company: 'Target', domain: 'corporate.target.com' },
  { company: 'Home Depot', domain: 'careers.homedepot.com' },
  { company: 'Verizon', domain: 'www.verizon.com' },
  { company: 'AT&T', domain: 'www.att.jobs' },
  { company: 'Boeing', domain: 'jobs.boeing.com' },
  { company: 'United Airlines', domain: 'careers.united.com' },
  { company: 'Cigna', domain: 'jobs.cigna.com' },
];
