export type QueryRule = {
  query: string;
  keywords: string[];
  requiredKeywords?: string[];
  minScore?: number;
};

export const JOB_BOARD_HOSTS = ['linkedin.com', 'glassdoor.com', 'indeed.com'];

export const ROLE_QUERY_RULES: QueryRule[] = [
  {
    query: 'software engineer',
    keywords: ['software', 'engineering', 'developer', 'development', 'web'],
  },
  {
    query: 'frontend engineer',
    keywords: ['frontend', 'react', 'user interface', 'ui', 'user experience', 'ux'],
  },
  {
    query: 'backend engineer',
    keywords: [
      'backend',
      'api',
      'microservices',
      'serverless',
      'node',
      'python',
      'java',
      'golang',
      'ruby',
      'php',
      'dotnet',
    ],
  },
  {
    query: 'fullstack engineer',
    keywords: ['fullstack', 'full stack'],
  },
  {
    query: 'devops engineer',
    keywords: [
      'devops',
      'sre',
      'site reliability',
      'kubernetes',
      'docker',
      'terraform',
      'ansible',
      'cloud',
      'aws',
      'gcp',
      'azure',
    ],
    requiredKeywords: ['devops', 'sre', 'site reliability'],
  },
  {
    query: 'mobile engineer',
    keywords: ['mobile', 'ios', 'android', 'react native'],
  },
  {
    query: 'data analyst',
    keywords: [
      'data analysis',
      'data analytics',
      'analytics',
      'business intelligence',
      'sql',
      'dashboard',
      'reporting',
      'tableau',
      'power bi',
      'excel',
    ],
  },
  {
    query: 'data scientist',
    keywords: [
      'data science',
      'data scientist',
      'machine learning',
      'statistics',
      'predictive modeling',
      'experimentation',
      'a/b testing',
    ],
  },
  {
    query: 'data engineer',
    keywords: [
      'data engineering',
      'etl',
      'data warehouse',
      'bigquery',
      'snowflake',
    ],
  },
  {
    query: 'product manager',
    keywords: ['product management', 'product manager', 'product strategy', 'roadmap'],
  },
  {
    query: 'project manager',
    keywords: [
      'project management',
      'project manager',
      'pmp',
      'scrum',
      'agile',
      'kanban',
      'jira',
      'stakeholder management',
      'requirements',
      'user stories',
    ],
  },
  {
    query: 'program manager',
    keywords: ['program management', 'program manager'],
  },
  {
    query: 'marketing manager',
    keywords: [
      'marketing',
      'digital marketing',
      'growth marketing',
      'performance marketing',
      'brand',
      'campaign management',
      'content marketing',
      'demand generation',
      'lead generation',
      'seo',
      'sem',
      'ppc',
      'paid search',
      'paid social',
      'email marketing',
      'marketing automation',
    ],
  },
  {
    query: 'account executive',
    keywords: [
      'account executive',
      'business development',
      'inside sales',
      'outside sales',
      'salesforce',
      'pipeline management',
      'lead generation',
    ],
  },
  {
    query: 'sales manager',
    keywords: [
      'sales',
      'account management',
      'sales operations',
      'revenue operations',
      'renewals',
      'upsell',
      'cross-sell',
    ],
  },
  {
    query: 'customer success manager',
    keywords: ['customer success', 'customer support', 'customer service'],
  },
  {
    query: 'financial analyst',
    keywords: [
      'finance',
      'financial analysis',
      'financial modeling',
      'budgeting',
      'forecasting',
      'fp&a',
      'treasury',
      'investments',
    ],
  },
  {
    query: 'accountant',
    keywords: [
      'accounting',
      'bookkeeping',
      'accounts payable',
      'accounts receivable',
      'gaap',
      'audit',
      'tax',
      'controller',
      'cpa',
    ],
  },
  {
    query: 'hr manager',
    keywords: [
      'human resources',
      'people operations',
      'performance management',
      'compensation',
      'benefits',
      'payroll',
      'hris',
      'employee relations',
    ],
  },
  {
    query: 'recruiter',
    keywords: ['recruiting', 'talent acquisition', 'talent management', 'onboarding'],
  },
  {
    query: 'operations manager',
    keywords: [
      'operations',
      'supply chain',
      'logistics',
      'procurement',
      'inventory',
      'warehouse',
      'fulfillment',
      'shipping',
      'transportation',
    ],
  },
  {
    query: 'product designer',
    keywords: [
      'product design',
      'user experience',
      'user interface',
      'ux research',
      'user research',
      'interaction design',
      'figma',
    ],
  },
  {
    query: 'graphic designer',
    keywords: [
      'graphic design',
      'visual design',
      'branding',
      'typography',
      'illustrator',
      'photoshop',
      'indesign',
      'motion design',
      'video editing',
    ],
  },
  {
    query: 'registered nurse',
    keywords: ['nursing', 'nurse', 'patient care', 'clinical', 'medical'],
  },
  {
    query: 'teacher',
    keywords: [
      'education',
      'teaching',
      'teacher',
      'curriculum',
      'instruction',
      'lesson planning',
      'classroom',
    ],
  },
  {
    query: 'instructional designer',
    keywords: ['instructional design', 'lms', 'edtech'],
  },
  {
    query: 'paralegal',
    keywords: ['legal', 'paralegal', 'litigation', 'contracts'],
  },
  {
    query: 'compliance analyst',
    keywords: [
      'compliance',
      'regulatory',
      'privacy',
      'gdpr',
      'policy',
      'governance',
      'ethics',
    ],
  },
  {
    query: 'process engineer',
    keywords: [
      'process engineering',
      'manufacturing',
      'production',
      'quality assurance',
      'quality control',
      'lean',
      'six sigma',
    ],
  },
  {
    query: 'mechanical engineer',
    keywords: ['mechanical', 'cad', 'autocad', 'solidworks'],
  },
  {
    query: 'construction manager',
    keywords: ['construction', 'site management', 'safety', 'osha'],
  },
  {
    query: 'field service technician',
    keywords: ['maintenance', 'field service'],
  },
  {
    query: 'hotel manager',
    keywords: ['hospitality', 'hotel', 'event planning', 'tourism'],
  },
  {
    query: 'restaurant manager',
    keywords: ['restaurant', 'food service'],
  },
  {
    query: 'retail manager',
    keywords: ['retail', 'merchandising', 'store operations', 'customer experience'],
  },
  {
    query: 'property manager',
    keywords: ['real estate', 'property management', 'leasing', 'mortgage'],
  },
  {
    query: 'insurance analyst',
    keywords: ['insurance', 'underwriting', 'claims', 'actuarial'],
  },
  {
    query: 'nonprofit program manager',
    keywords: [
      'nonprofit',
      'grant writing',
      'fundraising',
      'community outreach',
      'program evaluation',
    ],
  },
  {
    query: 'sustainability analyst',
    keywords: [
      'energy',
      'renewable energy',
      'utilities',
      'oil and gas',
      'sustainability',
      'environmental',
    ],
  },
];

export const TITLE_TOKENS = [
  'engineer',
  'developer',
  'designer',
  'manager',
  'analyst',
  'scientist',
  'architect',
  'consultant',
  'specialist',
  'coordinator',
  'administrator',
  'strategist',
  'director',
  'producer',
  'technician',
  'recruiter',
  'nurse',
  'teacher',
  'paralegal',
  'accountant',
  'executive',
  'assistant',
];

export const SKILL_HINTS = [
  'typescript',
  'javascript',
  'react',
  'react native',
  'node',
  'python',
  'java',
  'golang',
  'ruby',
  'php',
  'dotnet',
  'aws',
  'gcp',
  'azure',
  'kubernetes',
  'docker',
  'terraform',
  'sql',
  'tableau',
  'power bi',
  'excel',
  'salesforce',
  'hubspot',
  'marketo',
  'google analytics',
  'google ads',
  'adwords',
  'meta ads',
  'figma',
  'adobe',
  'photoshop',
  'illustrator',
  'indesign',
];

export const RESUME_TITLE_TOKENS = [
  ...TITLE_TOKENS,
  'founder',
  'owner',
  'president',
  'officer',
  'intern',
];

export const EXPERIENCE_HEADERS = [
  'experience',
  'work experience',
  'professional experience',
  'employment',
  'employment history',
  'work history',
  'career history',
];

export const SECTION_HEADERS = [
  ...EXPERIENCE_HEADERS,
  'education',
  'skills',
  'projects',
  'certifications',
  'certificates',
  'awards',
  'summary',
  'profile',
  'volunteer',
  'publications',
  'interests',
  'references',
  'activities',
  'languages',
  'training',
];

export const TITLE_SEPARATORS = [' - ', ' – ', ' | ', ' @ ', ' at ', ', '];

export const STATE_FALLBACK_CITIES: Record<string, string[]> = {
  AL: ['Birmingham, AL', 'Mobile, AL'],
  AK: ['Anchorage, AK'],
  AZ: ['Phoenix, AZ', 'Tucson, AZ'],
  AR: ['Little Rock, AR'],
  CA: ['Los Angeles, CA', 'San Francisco, CA', 'San Diego, CA'],
  CO: ['Denver, CO', 'Colorado Springs, CO'],
  CT: ['Hartford, CT'],
  DE: ['Wilmington, DE'],
  FL: ['Miami, FL', 'Orlando, FL', 'Tampa, FL'],
  GA: ['Atlanta, GA'],
  HI: ['Honolulu, HI'],
  ID: ['Boise, ID'],
  IL: ['Chicago, IL'],
  IN: ['Indianapolis, IN'],
  IA: ['Des Moines, IA'],
  KS: ['Wichita, KS'],
  KY: ['Louisville, KY'],
  LA: ['New Orleans, LA', 'Baton Rouge, LA'],
  ME: ['Portland, ME'],
  MD: ['Baltimore, MD'],
  MA: ['Boston, MA'],
  MI: ['Detroit, MI'],
  MN: ['Minneapolis, MN', 'St. Paul, MN'],
  MS: ['Jackson, MS'],
  MO: ['Kansas City, MO', 'St. Louis, MO'],
  MT: ['Billings, MT'],
  NE: ['Omaha, NE'],
  NV: ['Las Vegas, NV'],
  NH: ['Manchester, NH'],
  NJ: ['Newark, NJ'],
  NM: ['Albuquerque, NM'],
  NY: ['New York, NY', 'Buffalo, NY'],
  NC: ['Charlotte, NC', 'Raleigh, NC'],
  ND: ['Fargo, ND'],
  OH: ['Columbus, OH', 'Cleveland, OH'],
  OK: ['Oklahoma City, OK'],
  OR: ['Portland, OR'],
  PA: ['Philadelphia, PA', 'Pittsburgh, PA'],
  RI: ['Providence, RI'],
  SC: ['Charleston, SC'],
  SD: ['Sioux Falls, SD'],
  TN: ['Nashville, TN', 'Memphis, TN'],
  TX: ['Dallas, TX', 'Houston, TX', 'Austin, TX'],
  UT: ['Salt Lake City, UT'],
  VT: ['Burlington, VT'],
  VA: ['Richmond, VA'],
  WA: ['Seattle, WA'],
  WV: ['Charleston, WV'],
  WI: ['Milwaukee, WI'],
  WY: ['Cheyenne, WY'],
  DC: ['Washington, DC'],
};

export const STATE_NAME_TO_CODE: Record<string, string> = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  'new hampshire': 'NH',
  'new jersey': 'NJ',
  'new mexico': 'NM',
  'new york': 'NY',
  'north carolina': 'NC',
  'north dakota': 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  'rhode island': 'RI',
  'south carolina': 'SC',
  'south dakota': 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  'west virginia': 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
  'district of columbia': 'DC',
};
