export const KNOWN_KEYWORDS = [
  'software',
  'engineering',
  'developer',
  'development',
  'web',
  'frontend',
  'backend',
  'fullstack',
  'full stack',
  'mobile',
  'ios',
  'android',
  'react',
  'react native',
  'typescript',
  'javascript',
  'node',
  'nest',
  'graphql',
  'rest',
  'api',
  'microservices',
  'serverless',
  'cloud',
  'aws',
  'gcp',
  'azure',
  'devops',
  'sre',
  'site reliability',
  'docker',
  'kubernetes',
  'terraform',
  'ansible',
  'linux',
  'python',
  'java',
  'c#',
  'csharp',
  'c++',
  'golang',
  'ruby',
  'rails',
  'php',
  'dotnet',
  'testing',
  'observability',
  'performance',
  'accessibility',
  'security',
  'cybersecurity',
  'networking',
  'database',
  'postgres',
  'mysql',
  'redis',
  'mongodb',
  'data engineering',
  'data analysis',
  'data analytics',
  'data science',
  'data scientist',
  'data analyst',
  'business intelligence',
  'analytics',
  'sql',
  'excel',
  'tableau',
  'power bi',
  'dashboard',
  'reporting',
  'etl',
  'data warehouse',
  'bigquery',
  'snowflake',
  'statistics',
  'machine learning',
  'predictive modeling',
  'experimentation',
  'a/b testing',
  'product management',
  'product manager',
  'product strategy',
  'roadmap',
  'project management',
  'project manager',
  'program management',
  'program manager',
  'scrum',
  'agile',
  'kanban',
  'jira',
  'pmp',
  'stakeholder management',
  'requirements',
  'user stories',
  'change management',
  'marketing',
  'digital marketing',
  'content marketing',
  'brand',
  'brand management',
  'branding',
  'seo',
  'sem',
  'ppc',
  'paid search',
  'paid social',
  'social media',
  'email marketing',
  'marketing automation',
  'demand generation',
  'lead generation',
  'growth marketing',
  'performance marketing',
  'campaign management',
  'copywriting',
  'communications',
  'public relations',
  'media relations',
  'event marketing',
  'google analytics',
  'google ads',
  'adwords',
  'meta ads',
  'facebook ads',
  'linkedin ads',
  'hubspot',
  'marketo',
  'mailchimp',
  'content strategy',
  'creative strategy',
  'sales',
  'business development',
  'account executive',
  'account management',
  'customer success',
  'customer support',
  'customer service',
  'crm',
  'salesforce',
  'pipeline management',
  'sales operations',
  'revenue operations',
  'renewals',
  'upsell',
  'cross-sell',
  'inside sales',
  'outside sales',
  'finance',
  'financial analysis',
  'financial modeling',
  'accounting',
  'bookkeeping',
  'accounts payable',
  'accounts receivable',
  'gaap',
  'audit',
  'tax',
  'budgeting',
  'forecasting',
  'fp&a',
  'treasury',
  'investments',
  'portfolio management',
  'risk management',
  'controller',
  'cpa',
  'human resources',
  'people operations',
  'recruiting',
  'talent acquisition',
  'talent management',
  'onboarding',
  'employee relations',
  'performance management',
  'compensation',
  'benefits',
  'payroll',
  'hris',
  'learning and development',
  'training',
  'organizational development',
  'operations',
  'supply chain',
  'logistics',
  'procurement',
  'inventory',
  'warehouse',
  'fulfillment',
  'shipping',
  'transportation',
  'demand planning',
  'capacity planning',
  'quality management',
  'lean',
  'six sigma',
  'process improvement',
  'design',
  'graphic design',
  'visual design',
  'product design',
  'user experience',
  'user interface',
  'ux research',
  'user research',
  'interaction design',
  'figma',
  'adobe',
  'photoshop',
  'illustrator',
  'indesign',
  'typography',
  'motion design',
  'video editing',
  'healthcare',
  'clinical',
  'patient care',
  'nursing',
  'nurse',
  'medical',
  'physician',
  'hospital',
  'pharmacy',
  'therapist',
  'therapy',
  'physical therapy',
  'occupational therapy',
  'mental health',
  'behavioral health',
  'radiology',
  'laboratory',
  'biotech',
  'pharmaceutical',
  'public health',
  'ehr',
  'emr',
  'hipaa',
  'education',
  'teaching',
  'teacher',
  'curriculum',
  'instruction',
  'lesson planning',
  'classroom',
  'student',
  'higher education',
  'k-12',
  'instructional design',
  'lms',
  'edtech',
  'tutoring',
  'legal',
  'paralegal',
  'litigation',
  'contracts',
  'compliance',
  'regulatory',
  'privacy',
  'gdpr',
  'policy',
  'governance',
  'ethics',
  'manufacturing',
  'production',
  'quality assurance',
  'quality control',
  'process engineering',
  'mechanical',
  'electrical',
  'civil',
  'industrial',
  'automation',
  'cad',
  'autocad',
  'solidworks',
  'construction',
  'site management',
  'safety',
  'osha',
  'maintenance',
  'field service',
  'hospitality',
  'hotel',
  'restaurant',
  'food service',
  'retail',
  'merchandising',
  'store operations',
  'customer experience',
  'event planning',
  'travel',
  'tourism',
  'real estate',
  'property management',
  'leasing',
  'mortgage',
  'insurance',
  'underwriting',
  'claims',
  'actuarial',
  'nonprofit',
  'government',
  'public sector',
  'grant writing',
  'fundraising',
  'community outreach',
  'program evaluation',
  'energy',
  'renewable energy',
  'utilities',
  'oil and gas',
  'sustainability',
  'environmental',
  'ui',
];
